apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-18
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-18
  project: default
  source:
    repoURL: https://github.com/runezj/argocd-katas.git
    targetRevision: HEAD
    path: quotes-flask/helm/quotes-flask
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
